// flow-typed signature: f9bbd526c4ce9e873e9298ab40b913cd
// flow-typed version: <<STUB>>/import-sort_v^5.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-sort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-sort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-sort/lib/index' {
  declare module.exports: any;
}

declare module 'import-sort/lib/style/StyleAPI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-sort/lib/index.js' {
  declare module.exports: $Exports<'import-sort/lib/index'>;
}
declare module 'import-sort/lib/style/StyleAPI.js' {
  declare module.exports: $Exports<'import-sort/lib/style/StyleAPI'>;
}
