// flow-typed signature: 34608b3c04a5d3402bda267ca87cfc32
// flow-typed version: <<STUB>>/import-sort-style_v^5.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-sort-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-sort-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-sort-style/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-sort-style/lib/index.js' {
  declare module.exports: $Exports<'import-sort-style/lib/index'>;
}
