// flow-typed signature: a75c024fdf1b6dda62d0ea538ff3bef6
// flow-typed version: <<STUB>>/import-sort-style-module-grouping_v^0.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-sort-style-module-grouping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-sort-style-module-grouping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-sort-style-module-grouping/build/src/index' {
  declare module.exports: any;
}

declare module 'import-sort-style-module-grouping/src/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'import-sort-style-module-grouping/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-sort-style-module-grouping/build/src/index.js' {
  declare module.exports: $Exports<'import-sort-style-module-grouping/build/src/index'>;
}
declare module 'import-sort-style-module-grouping/src/__tests__/index.spec.js' {
  declare module.exports: $Exports<'import-sort-style-module-grouping/src/__tests__/index.spec'>;
}
declare module 'import-sort-style-module-grouping/src/index.js' {
  declare module.exports: $Exports<'import-sort-style-module-grouping/src/index'>;
}
